name: pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.3.5
  - pip=21.3.1
  - requests=2.24.0
  - hydra-core=1.1.1
  - pip:
      - wandb==0.12.9
      - mlflow==1.14.1
      - hydra-joblib-launcher==1.1.5
      - protobuf==3.20.*