main:
  project_name: mlops-final-project
  experiment_name: dev
data:
  train_data: "mlops-final-project/train_data.csv:latest"
decision_tree_pipeline:
  decision_tree:
    criterion: "entropy"
    splitter: "best"
    max_depth: null
  numerical_pipe:
    model: 0
  export_artifact: "null"